name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  clojure-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Prepare java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: 'latest'
    - name: Cache deps.edn, .shadow-cljs and node modules
      uses: actions/cache@v3
      with:
        path: |
          .shadow-cljs
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
          .cpcache
          node_modules
          resources
        key: ${{ runner.os }}-shadow-cljs-${{ hashFiles('deps.edn', 'package.json')}}
        restore-keys: |
          ${{ runner.os }}-shadow-cljs-
    - name: Run tests
      run: clojure -X:test


  shadow-cljs-compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Prepare java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: 'latest'
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Cache deps.edn, .shadow-cljs and node modules
      uses: actions/cache@v3
      with:
        path: |
          .shadow-cljs
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
          .cpcache
          node_modules
        key: ${{ runner.os }}-shadow-cljs-${{ hashFiles('deps.edn', 'package.json')}}
        restore-keys: |
          ${{ runner.os }}-shadow-cljs-
    - name: Install npm dependencies
      run: npm install
    - name: Compile shadow-cljs app
      run: clojure -M:shadow-cljs compile app
